language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
  - npm install codecov -g
script:
- ng lint
- ng build
- npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
after_success:
  - codecov
